package name.generator.utils;

import java.util.AbstractMap;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class TestsUtils {

	private TestsUtils() {
	}

	public static final String TEST_SEED = "MyTestSeed";

	public static final Map<String, String> REPLACED_NAMES_WORD = Map.ofEntries(
			new AbstractMap.SimpleEntry<String, String>("feather", "Gothitelle"),
			new AbstractMap.SimpleEntry<String, String>("yogurt", "Bramblin"),
			new AbstractMap.SimpleEntry<String, String>("vortex", "Greavard"),
			new AbstractMap.SimpleEntry<String, String>("xerox", "Happiny"),
			new AbstractMap.SimpleEntry<String, String>("rocket", "Inteleon"),
			new AbstractMap.SimpleEntry<String, String>("kangaroo", "Skarmory"),
			new AbstractMap.SimpleEntry<String, String>("echo", "Dusknoir"),
			new AbstractMap.SimpleEntry<String, String>("xenon", "Pancham"),
			new AbstractMap.SimpleEntry<String, String>("dragon", "Iranian"),
			new AbstractMap.SimpleEntry<String, String>("mountain", "Kingambit"),
			new AbstractMap.SimpleEntry<String, String>("kitten", "Porygon"),
			new AbstractMap.SimpleEntry<String, String>("hazard", "Shaymin"),
			new AbstractMap.SimpleEntry<String, String>("orbit", "Raccoon"),
			new AbstractMap.SimpleEntry<String, String>("canvas", "Numel"),
			new AbstractMap.SimpleEntry<String, String>("whistle", "Klang"),
			new AbstractMap.SimpleEntry<String, String>("tiger", "Naclstack"),
			new AbstractMap.SimpleEntry<String, String>("yonder", "Mandibuzz"),
			new AbstractMap.SimpleEntry<String, String>("spectrum", "Sorcerer"),
			new AbstractMap.SimpleEntry<String, String>("jungle", "Leadership"),
			new AbstractMap.SimpleEntry<String, String>("forest", "Walnuts"),
			new AbstractMap.SimpleEntry<String, String>("mirror", "Freesia"),
			new AbstractMap.SimpleEntry<String, String>("pirate", "User"),
			new AbstractMap.SimpleEntry<String, String>("crystal", "Istanbul"),
			new AbstractMap.SimpleEntry<String, String>("jewel", "Skiploom"),
			new AbstractMap.SimpleEntry<String, String>("utility", "Anaconda"),
			new AbstractMap.SimpleEntry<String, String>("noodle", "Baseball"),
			new AbstractMap.SimpleEntry<String, String>("helmet", "Flapple"),
			new AbstractMap.SimpleEntry<String, String>("quiet", "Loudred"),
			new AbstractMap.SimpleEntry<String, String>("volcano", "Ankara"),
			new AbstractMap.SimpleEntry<String, String>("daisy", "Magneton"),
			new AbstractMap.SimpleEntry<String, String>("scooter", "Mewtwo"),
			new AbstractMap.SimpleEntry<String, String>("meadow", "Lickitung"),
			new AbstractMap.SimpleEntry<String, String>("raven", "Talonflame"),
			new AbstractMap.SimpleEntry<String, String>("kernel", "License"),
			new AbstractMap.SimpleEntry<String, String>("nest", "Aromatisse"),
			new AbstractMap.SimpleEntry<String, String>("lantern", "Azalea"),
			new AbstractMap.SimpleEntry<String, String>("token", "Drowzee"),
			new AbstractMap.SimpleEntry<String, String>("radar", "Zebstrika"),
			new AbstractMap.SimpleEntry<String, String>("anchor", "Gible"),
			new AbstractMap.SimpleEntry<String, String>("candle", "Combee"),
			new AbstractMap.SimpleEntry<String, String>("sunset", "Berserker"),
			new AbstractMap.SimpleEntry<String, String>("zipper", "Quaxwell"),
			new AbstractMap.SimpleEntry<String, String>("river", "Dresser"),
			new AbstractMap.SimpleEntry<String, String>("desert", "Khajit"),
			new AbstractMap.SimpleEntry<String, String>("unicorn", "Gardevoir"),
			new AbstractMap.SimpleEntry<String, String>("saddle", "Grovyle"),
			new AbstractMap.SimpleEntry<String, String>("owl", "Tyrogue"),
			new AbstractMap.SimpleEntry<String, String>("quest", "Migrator"),
			new AbstractMap.SimpleEntry<String, String>("cloud", "Spoink"),
			new AbstractMap.SimpleEntry<String, String>("waffle", "Hamburg"),
			new AbstractMap.SimpleEntry<String, String>("igloo", "Pyroar"),
			new AbstractMap.SimpleEntry<String, String>("insect", "Karrablast"),
			new AbstractMap.SimpleEntry<String, String>("alley", "Place"),
			new AbstractMap.SimpleEntry<String, String>("oxygen", "SouthAfrican"),
			new AbstractMap.SimpleEntry<String, String>("notebook", "Archeops"),
			new AbstractMap.SimpleEntry<String, String>("banana", "Quaxly"),
			new AbstractMap.SimpleEntry<String, String>("avocado", "French"),
			new AbstractMap.SimpleEntry<String, String>("dolphin", "Interface"),
			new AbstractMap.SimpleEntry<String, String>("koala", "Chimchar"),
			new AbstractMap.SimpleEntry<String, String>("island", "Cofagrigus"),
			new AbstractMap.SimpleEntry<String, String>("jacket", "Bagon"),
			new AbstractMap.SimpleEntry<String, String>("breeze", "Riolu"),
			new AbstractMap.SimpleEntry<String, String>("grape", "Minun"),
			new AbstractMap.SimpleEntry<String, String>("fossil", "Nuzleaf"),
			new AbstractMap.SimpleEntry<String, String>("voyage", "Silcoon"),
			new AbstractMap.SimpleEntry<String, String>("marble", "Nightstand"),
			new AbstractMap.SimpleEntry<String, String>("ocean", "Brussels"),
			new AbstractMap.SimpleEntry<String, String>("trumpet", "Accelgor"),
			new AbstractMap.SimpleEntry<String, String>("eagle", "Courgette"),
			new AbstractMap.SimpleEntry<String, String>("valley", "Cod"),
			new AbstractMap.SimpleEntry<String, String>("emerald", "Electivire"),
			new AbstractMap.SimpleEntry<String, String>("xylophone", "Software"),
			new AbstractMap.SimpleEntry<String, String>("hammer", "Rhyhorn"),
			new AbstractMap.SimpleEntry<String, String>("lighthouse", "Salamence"),
			new AbstractMap.SimpleEntry<String, String>("groove", "Treecko"),
			new AbstractMap.SimpleEntry<String, String>("update", "Jirachi"),
			new AbstractMap.SimpleEntry<String, String>("quiver", "Dudunsparce"),
			new AbstractMap.SimpleEntry<String, String>("apple", "Cable"),
			new AbstractMap.SimpleEntry<String, String>("lemon", "Diggersby"),
			new AbstractMap.SimpleEntry<String, String>("engine", "Abra"),
			new AbstractMap.SimpleEntry<String, String>("honey", "Chimpanzee"),
			new AbstractMap.SimpleEntry<String, String>("treasure", "Ham"),
			new AbstractMap.SimpleEntry<String, String>("glacier", "Sweets"),
			new AbstractMap.SimpleEntry<String, String>("zebra", "Recycled"),
			new AbstractMap.SimpleEntry<String, String>("butter", "Meowstic"),
			new AbstractMap.SimpleEntry<String, String>("umbrella", "Two"),
			new AbstractMap.SimpleEntry<String, String>("yawn", "Spreadsheet"),
			new AbstractMap.SimpleEntry<String, String>("zenith", "Helioptile"),
			new AbstractMap.SimpleEntry<String, String>("quartz", "Beedrill"),
			new AbstractMap.SimpleEntry<String, String>("nectar", "Browser"),
			new AbstractMap.SimpleEntry<String, String>("pencil", "Duskull"),
			new AbstractMap.SimpleEntry<String, String>("ivy", "Psyduck"),
			new AbstractMap.SimpleEntry<String, String>("guitar", "Internal"),
			new AbstractMap.SimpleEntry<String, String>("pebble", "Eldegoss"),
			new AbstractMap.SimpleEntry<String, String>("ladder", "Cream"),
			new AbstractMap.SimpleEntry<String, String>("puzzle", "Cot"),
			new AbstractMap.SimpleEntry<String, String>("blanket", "Fox"),
			new AbstractMap.SimpleEntry<String, String>("window", "Amoonguss"),
			new AbstractMap.SimpleEntry<String, String>("flame", "Lurantis"));

	public static final Map<String, String> REPLACED_NAMES_NUMBER = Map.ofEntries(
			new AbstractMap.SimpleEntry<String, String>("feather", "Coconut"),
			new AbstractMap.SimpleEntry<String, String>("yogurt", "Nutmeg"),
			new AbstractMap.SimpleEntry<String, String>("vortex", "Page"),
			new AbstractMap.SimpleEntry<String, String>("xerox", "Githyanki"),
			new AbstractMap.SimpleEntry<String, String>("rocket", "Wattrel"),
			new AbstractMap.SimpleEntry<String, String>("kangaroo", "Chicken"),
			new AbstractMap.SimpleEntry<String, String>("echo", "Vinaigrette"),
			new AbstractMap.SimpleEntry<String, String>("xenon", "Tinkatink"),
			new AbstractMap.SimpleEntry<String, String>("dragon", "Golbat"),
			new AbstractMap.SimpleEntry<String, String>("mountain", "Hind"),
			new AbstractMap.SimpleEntry<String, String>("kitten", "Private"),
			new AbstractMap.SimpleEntry<String, String>("hazard", "Inkay"),
			new AbstractMap.SimpleEntry<String, String>("orbit", "Delhi"),
			new AbstractMap.SimpleEntry<String, String>("canvas", "Money"),
			new AbstractMap.SimpleEntry<String, String>("whistle", "Smeargle"),
			new AbstractMap.SimpleEntry<String, String>("tiger", "Dodrio"),
			new AbstractMap.SimpleEntry<String, String>("yonder", "Sole"),
			new AbstractMap.SimpleEntry<String, String>("spectrum", "Machop"),
			new AbstractMap.SimpleEntry<String, String>("jungle", "Fletchinder"),
			new AbstractMap.SimpleEntry<String, String>("forest", "Espurr"),
			new AbstractMap.SimpleEntry<String, String>("mirror", "Cyndaquil"),
			new AbstractMap.SimpleEntry<String, String>("pirate", "ChienPao"),
			new AbstractMap.SimpleEntry<String, String>("crystal", "Marshtomp"),
			new AbstractMap.SimpleEntry<String, String>("jewel", "Clawitzer"),
			new AbstractMap.SimpleEntry<String, String>("utility", "Brambleghast"),
			new AbstractMap.SimpleEntry<String, String>("noodle", "Coalossal"),
			new AbstractMap.SimpleEntry<String, String>("helmet", "Snover"),
			new AbstractMap.SimpleEntry<String, String>("quiet", "Fearow"),
			new AbstractMap.SimpleEntry<String, String>("volcano", "Sentret"),
			new AbstractMap.SimpleEntry<String, String>("daisy", "Claydol"),
			new AbstractMap.SimpleEntry<String, String>("scooter", "Modem"),
			new AbstractMap.SimpleEntry<String, String>("meadow", "Paris"),
			new AbstractMap.SimpleEntry<String, String>("raven", "Ariados"),
			new AbstractMap.SimpleEntry<String, String>("kernel", "FlutterMane"),
			new AbstractMap.SimpleEntry<String, String>("nest", "Glimmet"),
			new AbstractMap.SimpleEntry<String, String>("lantern", "Drifloon"),
			new AbstractMap.SimpleEntry<String, String>("token", "Monitor"),
			new AbstractMap.SimpleEntry<String, String>("radar", "Connected"),
			new AbstractMap.SimpleEntry<String, String>("anchor", "Starfish"),
			new AbstractMap.SimpleEntry<String, String>("candle", "Delcatty"),
			new AbstractMap.SimpleEntry<String, String>("sunset", "Minior"),
			new AbstractMap.SimpleEntry<String, String>("zipper", "Frankfurt"),
			new AbstractMap.SimpleEntry<String, String>("river", "Algerian"),
			new AbstractMap.SimpleEntry<String, String>("desert", "Skarmory"),
			new AbstractMap.SimpleEntry<String, String>("unicorn", "Tangrowth"),
			new AbstractMap.SimpleEntry<String, String>("saddle", "Beedrill"),
			new AbstractMap.SimpleEntry<String, String>("owl", "Kidneys"),
			new AbstractMap.SimpleEntry<String, String>("quest", "Golisopod"),
			new AbstractMap.SimpleEntry<String, String>("cloud", "Dragonite"),
			new AbstractMap.SimpleEntry<String, String>("waffle", "Dingo"),
			new AbstractMap.SimpleEntry<String, String>("igloo", "Vigoroth"),
			new AbstractMap.SimpleEntry<String, String>("insect", "Indicator"),
			new AbstractMap.SimpleEntry<String, String>("alley", "Togekiss"),
			new AbstractMap.SimpleEntry<String, String>("oxygen", "Auckland"),
			new AbstractMap.SimpleEntry<String, String>("notebook", "Golf"),
			new AbstractMap.SimpleEntry<String, String>("banana", "Egyptian"),
			new AbstractMap.SimpleEntry<String, String>("avocado", "Platypus"),
			new AbstractMap.SimpleEntry<String, String>("dolphin", "Cursola"),
			new AbstractMap.SimpleEntry<String, String>("koala", "Xerneas"),
			new AbstractMap.SimpleEntry<String, String>("island", "Combusken"),
			new AbstractMap.SimpleEntry<String, String>("jacket", "Otter"),
			new AbstractMap.SimpleEntry<String, String>("breeze", "Avalugg"),
			new AbstractMap.SimpleEntry<String, String>("grape", "Bellibolt"),
			new AbstractMap.SimpleEntry<String, String>("fossil", "Binacle"),
			new AbstractMap.SimpleEntry<String, String>("voyage", "Lumineon"),
			new AbstractMap.SimpleEntry<String, String>("marble", "Klefki"),
			new AbstractMap.SimpleEntry<String, String>("ocean", "Hariyama"),
			new AbstractMap.SimpleEntry<String, String>("trumpet", "Chimchar"),
			new AbstractMap.SimpleEntry<String, String>("eagle", "Dracovish"),
			new AbstractMap.SimpleEntry<String, String>("valley", "Data"),
			new AbstractMap.SimpleEntry<String, String>("emerald", "Virtual"),
			new AbstractMap.SimpleEntry<String, String>("xylophone", "Swadloon"),
			new AbstractMap.SimpleEntry<String, String>("hammer", "Employee"),
			new AbstractMap.SimpleEntry<String, String>("lighthouse", "Debug"),
			new AbstractMap.SimpleEntry<String, String>("groove", "Japanese"),
			new AbstractMap.SimpleEntry<String, String>("update", "Espeon"),
			new AbstractMap.SimpleEntry<String, String>("quiver", "Tablet"),
			new AbstractMap.SimpleEntry<String, String>("apple", "Axew"),
			new AbstractMap.SimpleEntry<String, String>("lemon", "Warden"),
			new AbstractMap.SimpleEntry<String, String>("engine", "Lemur"),
			new AbstractMap.SimpleEntry<String, String>("honey", "SanFrancisco"),
			new AbstractMap.SimpleEntry<String, String>("treasure", "Weepinbell"),
			new AbstractMap.SimpleEntry<String, String>("glacier", "Chesnaught"),
			new AbstractMap.SimpleEntry<String, String>("zebra", "Landorus"),
			new AbstractMap.SimpleEntry<String, String>("butter", "Thai"),
			new AbstractMap.SimpleEntry<String, String>("umbrella", "Sliggoo"),
			new AbstractMap.SimpleEntry<String, String>("yawn", "Lairon"),
			new AbstractMap.SimpleEntry<String, String>("zenith", "Raisins"),
			new AbstractMap.SimpleEntry<String, String>("quartz", "Ralts"),
			new AbstractMap.SimpleEntry<String, String>("nectar", "Orchid"),
			new AbstractMap.SimpleEntry<String, String>("pencil", "Utils"),
			new AbstractMap.SimpleEntry<String, String>("ivy", "Karrablast"),
			new AbstractMap.SimpleEntry<String, String>("guitar", "Chansey"),
			new AbstractMap.SimpleEntry<String, String>("pebble", "Flabebe"),
			new AbstractMap.SimpleEntry<String, String>("ladder", "Live"),
			new AbstractMap.SimpleEntry<String, String>("puzzle", "Megabyte"),
			new AbstractMap.SimpleEntry<String, String>("blanket", "Quality"),
			new AbstractMap.SimpleEntry<String, String>("window", "SlitherWing"),
			new AbstractMap.SimpleEntry<String, String>("flame", "Call"));

	// Need to be sorted to ensure test consistency with the random seed
	public static final List<String> INITIAL_NAMES = REPLACED_NAMES_NUMBER.keySet().stream().sorted().toList();
	// public static final List<String> EXPECTED_REPLACED_NAMES =
	// REPLACED_NAMES.keySet().stream().toList();

	public static final List<String> THOUSAND_NAMES_NUMBER_EXPECTED = Arrays.asList("Combusken", "Belgrade",
			"Pheromosa3", "Pheromosa2", "Server", "Bewear", "Falcon", "Electrike", "Bisharp2", "IronJugulis", "Zygarde",
			"Staraptor", "Milk", "Lunatone2", "Finneon", "Espeon", "Lisbon", "Dragalge", "Azalea", "Employee",
			"Stockholm3", "Stockholm2", "Analog", "Pawmi", "TigerLily", "Gurdurr", "Noodles2", "Dragonite",
			"Ranunculus", "Crocus", "Merchant", "Indonesian", "Vullaby", "Necromancer", "Trumbeak", "Platypus",
			"Trampoline", "Gardevoir", "Geodude2", "Decidueye", "Shaymin", "Omastar", "Dondozo", "Competitive",
			"Weedle", "Artichoke", "Golduck", "Parameter", "Geodude3", "Margarine", "Thwackey", "Tranquill",
			"Reuniclus2", "Hydreigon2", "Email", "Salazzle", "Recliner", "Liver", "Swadloon", "Omanyte", "Arcanine",
			"Tiefling", "Frogadier", "Cosmog", "Swimming", "Control2", "Ekans", "Protected", "Boxing", "Trubbish",
			"Zigzagoon", "Houndoom", "Sentret", "Commercial2", "Goodra", "Sydney2", "Squawkabilly2", "Zamazenta",
			"Shooting", "Lobelia", "Cascoon", "Manila", "Hatterene", "Kricketune", "Banette", "Sole", "Petilil2", "Vpn",
			"Sealeo", "Cloyster", "Proposition", "Klefki", "Kipper", "Spidops", "Cobalion", "Charizard", "Slaking",
			"TapuKoko", "Hibiscus", "Giratina", "Indicator", "Weepinbell", "Chansey", "Jellyfish", "Apple", "Mouse",
			"Technology2", "Wishiwashi", "Ninetales", "Indian", "Boltund", "Mustard", "Online2", "Nickit", "Gible",
			"Dolphin", "RoaringMoon2", "Honeysuckle", "Apricot", "Foongus", "Peacock", "Ukrainian", "Orbeetle",
			"Footstool", "Salamander", "Phione", "Budew", "Mareep", "Crabominable", "Gible2", "Accelgor", "Zinnia",
			"Bounsweet", "Tank", "Deer", "Blastoise", "Marowak2", "Cherubi", "Avocado", "Weavile", "Arrokuda", "Margin",
			"Wingull2", "MrRime2", "Draw", "American", "Supply", "Braviary", "Simisage", "Cleffa", "Ponyta2",
			"TasmanianDevil", "Pastry2", "Rattlesnake", "Commode", "Property", "Panpour", "Dragonborn", "Cot", "Pig",
			"Blissey", "Vietnamese", "Electivire", "Milotic", "Elgyem", "Luxray", "Indeedee", "Penguin", "Sausages",
			"Decompressed", "FlutterMane", "Shuppet", "Miltank", "Gholdengo", "Electrode2", "Delphinium", "Random",
			"Blacephalon", "Venusaur", "Blitzle", "Toxtricity", "Thai", "Shinx", "Disk", "Venonat", "Volleyball",
			"Salmon", "Wiglett", "Pumpkaboo", "Heatmor", "Vulnerability", "Public", "Quagsire", "Invent", "Skarmory",
			"Eelektrik", "Swablu", "Mayonnaise", "BunkBed", "Scatterbug", "Golett", "Applin", "File", "Sultanas",
			"Frankfurt", "Dynamic", "Zacian", "Chandelure", "Calyrex", "Fletchling", "Doublade", "Elgyem2", "Sunkern",
			"Tv2", "Format", "Phone", "Melmetal", "Raccoon", "Lunatone", "Spewpa", "Sugar", "Beetroot", "Tennis",
			"Cobra", "Hoppip", "Reshiram", "Intern", "Greninja2", "Oranguru", "Virtual", "Regirock", "Chimchar",
			"Camerupt", "Array", "Whale", "Charcadet", "Sausage2", "Sheep", "Jumpluff", "Geodude", "Turtwig", "Houston",
			"Pork2", "Charmander", "BuenosAires", "Badminton", "Volbeat", "Glastrier", "Talonflame", "Stunfisk",
			"Anaconda", "Kenyan", "Honedge", "Regigigas", "Abomasnow", "Dynamic2", "Sawsbuck", "Purrloin", "Phantump",
			"Purugly", "Deoxys2", "Herbs", "Jolteon", "Dependency", "Two", "Ostrich", "Snorunt", "Diancie", "Lokix",
			"Duraludon", "Swoobat", "Granbull", "Frigibax", "Coyote", "Comfey", "Sprigatito", "Sydney", "Chesnaught2",
			"Mabosstiff", "Chesnaught3", "Girafarig", "Sliggoo2", "Marshadow", "Steelix", "Dubai", "Open", "Chilean",
			"Pineapple", "Tyranitar2", "Zeraora", "Noivern", "Mesprit2", "Throh", "Chocolate", "Cubchoo", "Rampardos",
			"Palossand", "Barboach", "Malamar", "Guadalajara2", "Glimmet", "Munchlax", "RockingChair", "IronTreads",
			"Feraligatr", "Yield", "Toucannon", "Greninja", "IronBoulder2", "Dustox", "Manager", "Ferroseed",
			"Stantler", "Chesnaught", "Flittle2", "GrizzlyBear", "Grapploct", "Beautifly", "Swinub", "Mudsdale",
			"Kakuna", "Vanillite", "Miraidon", "Tv", "Electrode", "Kirlia", "Cyndaquil", "Timburr", "Entei", "Lilac",
			"Hind", "Drampa", "Amaura", "Kricketot", "Class", "Cofagrigus", "Seel", "Italian", "Bangladeshi",
			"Sudowoodo", "Shelf", "Review", "Basketball", "Unown", "Sinistea", "Wobbuffet", "Excadrill", "Bard",
			"Milcery", "Tyrogue", "Sizzlipede", "Wimpod", "SaoPaulo", "Dondozo2", "Zero", "Minccino", "Bisharp",
			"Miami", "Samurott", "Larvesta", "Sandaconda", "Ankara", "Pasta", "Woobat", "Croconaw", "Gimmighoul",
			"Leafeon", "Melon", "Leadership", "Quiche", "Shark", "CornFlour", "Wugtrio", "Dodrio", "Demon2", "Shared",
			"Bacon", "Whimsicott", "Training", "Marowak", "Cricket", "Dracovish", "Network", "Database", "Computer",
			"Verbena", "Wifi", "Hippopotamus", "Local", "Offline", "Athens", "Staravia", "Helioptile", "Dwarf",
			"Sliggoo", "WashingtonDc", "Sylveon", "Cucumber", "Ferroseed2", "Noodles", "TapuBulu", "Delcatty",
			"Altaria", "Rampardos2", "Sorcerer", "Sneasler", "Yanma", "Frillish", "Mareanie", "Spam", "Clawitzer",
			"Victreebel", "Filipino", "Chrysanthemum", "Seoul", "Amsterdam", "Ursaluna", "Seedot", "Braviary2",
			"Eternatus", "Entei2", "Bufget", "Xatu", "Mantelpiece", "Prawns", "Psyduck", "Ludicolo", "Vileplume",
			"Vanillish", "Pecharunt", "Lotad", "Turnip", "Dartrix2", "Heracross", "Skorupi", "Fidough", "Serperior",
			"Secretaire", "Flittle", "Indeedee2", "Cream", "Hydrapple", "Update", "Litwick", "Prince", "Eight",
			"Technology", "Courgette", "BunkBed2", "Pincurchin", "Python", "Spinda", "Articuno", "Electabuzz", "Queen",
			"Media", "Probopass", "Stockholm", "Mudkip", "Munchlax2", "Kecleon", "Metang", "Drakloak", "Latios2",
			"Daffodil", "Xurkitree", "Pansear", "Aromatisse", "Skunk", "Blackberry", "Ledyba", "Digital", "IronLeaves",
			"Overqwil", "Lily", "Crocodile", "Chingling", "Chilli", "Crabrawler", "Dratini", "Scyther", "Feebas",
			"Togetic", "Frog", "Dracozolt", "Sage", "Taillow", "ScreamTail", "Commercial", "Zubat", "Fennekin",
			"Larkspur", "Mimikyu", "Malamar2", "Khajit", "Toedscruel", "HakamoO", "Charmeleon", "Brambleghast",
			"Dartrix", "Vinegar", "Swedish", "Begonia", "Design", "Suicune", "Gliscor", "Popup", "Clodsire", "Lion",
			"Paladin", "Zoroark", "Slurpuff", "Raikou", "Personal", "Dunsparce2", "Croagunk", "Goldeen", "Method",
			"Magnolia", "Sigilyph", "Tuna", "Riolu", "Bronzong", "Link", "Deino", "Kyurem", "Carvanha", "Rhinoceros",
			"Dugtrio", "Meltan", "Togedemaru", "Scovillain", "Mumbai", "Krabby", "Machop", "Cinccino", "Salt",
			"Magmortar", "Stufful", "Algerian", "Seadra", "Download", "Darmanitan", "Armchair", "Rowlet", "Toxapex",
			"Blipbug", "Bee", "Pidgey", "Poliwrath", "Thyme", "Clefable", "Eelektross", "Solgaleo", "Utils", "Vulpix",
			"Claydol2", "Montreal", "Abomasnow2", "Hattrem", "Pachirisu", "Munkidori", "Shiinotic", "Trevenant",
			"Mamoswine", "Pelipper", "Goblin", "Johannesburg", "Tynamo", "Watchog", "Scraggy", "Nairobi", "Espurr",
			"Version", "Clematis", "Barbarian2", "Reuniclus", "Ketchup", "Offline2", "MrRime", "Genesect2", "Syrian",
			"IronHands", "Scolipede", "Fox", "Prague", "Karrablast", "Raboot", "Sneasel", "Bulbasaur", "Carkol",
			"Espeon2", "Spices", "Jumpluff2", "Sunflower", "Weepinbell2", "Pork", "Explorer", "Cache", "Taipei",
			"Bellossom", "Necromancer2", "Terapagos", "Houndstone", "Squawkabilly", "Mexican", "Morgrem", "Fezandipiti",
			"Dottler", "Lairon", "Explorer2", "Lillipup", "Garbodor", "BeanSprouts", "Boldore", "Florges", "Chest",
			"Cranidos", "Lizard", "Noctowl", "Latios", "Lugia", "Slowbro", "Gastly", "Poltchageist", "Human",
			"Forsythia", "Keldeo", "Sausage", "Peas", "Armadillo", "Archaludon", "Onion", "HakamoO2", "Demon",
			"Biathlon", "Coriander", "Smoochum", "Eevee", "Kilowattrel", "Undo", "Japanese", "Luxio", "Magcargo",
			"Santiago", "Lobster", "Salmon2", "Baseball", "Grape", "Daisy", "Genesect", "Claydol", "Alomomola",
			"Cranidos2", "Magearna", "Chain", "Seahorse", "Chair", "Persian", "Accelgor2", "Upload", "Solosis",
			"Terrakion", "Piplup", "Galvantula", "Dewpider", "Drednaw", "Xerneas", "Loveseat", "Maschiff",
			"Corviknight", "Trapinch", "Makuhita", "Shedinja", "Usb", "Witcher", "Horsea", "Blackcurrant", "Frosmoth",
			"Salamence", "Mienfoo", "Tinkaton", "Klinklang", "MorningGlory", "Stingray", "Lickitung", "Mimikyu2",
			"Okidogi", "Hammock", "Aasimar", "Capsakid", "Chain2", "Ariados", "Essential", "Sceptile", "Yungoos",
			"Avalugg", "Hawk", "Volcanion", "Strawberry", "Swan", "Aggron", "Houston2", "SanFrancisco", "Walnuts",
			"Heather", "Hydreigon", "Organic", "PorygonZ", "Pakistani", "Enamorus", "Weightlifting", "GarterSnake",
			"Darumaka", "Sunflower2", "Tehran2", "Mew", "Nidoking", "Drowzee", "Koala", "TigerLily2", "Mackerel",
			"Hatenna", "Karrablast2", "Ninjask", "Dunsparce", "Vienna", "Sewaddle", "Petilil", "Fomantis", "Debug",
			"Tehran", "Cleffa2", "Polish", "Hockey", "Cutiefly", "Sawk", "Milotic2", "Mode", "Torterra", "Emboar",
			"Aerodactyl", "Mayonnaise2", "Aron", "Pupitar", "Golurk", "Drampa2", "Connected", "Snowdrop", "Mankey",
			"Grotle", "Bastiodon", "Sawk2", "Carracosta", "Mightyena", "Salami", "Nacli", "Eight2", "Kadabra",
			"Conkeldurr", "Eagle", "Ducklett", "Bidoof", "Cookie", "Krokorok", "Naganadel", "IronBoulder", "Afghan",
			"Mantine", "IronValiant", "Giraffe", "Pheromosa", "Sigilyph2", "Maractus", "Jirachi", "Bangladeshi2",
			"Swellow", "Key", "Nihilego", "Binacle", "Nincada", "Futsal", "Warden", "Flabebe", "Coalossal", "Inkay",
			"Golbat", "Hamburg", "Glalie", "Vivillon", "Glimmora", "Lucario", "Barbarian", "Slugma", "Forretress",
			"Cupboard", "Question", "Synergy", "Tablet", "Bougainvillea", "Extractor", "Gabite", "Palpitoad",
			"Greavard", "Shanghai", "Mushroom", "Popplio", "Headboard", "Exeggutor", "Dubwool", "Muesli", "Kingfisher",
			"Garlic", "RioDeJaneiro", "Vanity", "Furfrou", "Relicanth", "Kyoto", "Banette2", "Squirtle", "Zangoose",
			"Nigerian", "Prinplup", "Lemon", "Zurich", "Industry", "Potato", "Smoliv", "Portuguese", "Servine", "Klink",
			"Table2", "Guadalajara", "Saffron", "Tangela", "Rayquaza", "Mole", "Kingdra", "Oslo", "Floette", "Program",
			"Excadrill2", "Leavanny", "Dudunsparce", "Alstroemeria", "Giraffe2", "Broccoli", "Hedgehog", "Cramorant",
			"Flaaffy", "Internet", "Binary", "Static", "Grimmsnarl", "Laptop", "Torracat", "Aipom", "Singapore",
			"Ponyta", "Cakes", "Peach", "Durant", "Mesprit", "Control", "Glameow", "Electricity", "Breaking",
			"Tyranitar", "Iranian", "Ferrothorn", "Fletchinder", "Pawmot", "Tornadus", "Grookey", "Skiddo",
			"Tangrowth2", "Lopunny", "Piloswine", "Pancham", "Vampire", "Gorilla", "Archen", "Zip", "Wingull", "Raichu",
			"Guzzlord", "Internal", "Bronzong2", "NidoranMale", "Tropius", "Orange", "Crustle", "Cloyster2", "Item",
			"Veal", "Kathmandu", "Quaxwell", "Roselia", "Barbaracle", "Donphan", "Istanbul", "Grotle2", "Gligar",
			"Salamence2", "Ressource", "Deoxys", "Roserade", "Surfing", "Scorbunny", "Honey", "Turkey", "Spiritomb",
			"Condiments", "Browser", "Gorebyss", "Latias", "Artichoke2", "German", "Desktop2", "Camel", "Starly",
			"Spreadsheet", "Spinarak", "Partner", "Shelmet", "Yungoos2", "Table", "SirfetchD", "Greedent", "Korean",
			"Rhyperior", "Poochyena", "Otter", "Australian", "Swanna", "Hydrangea", "Tangrowth", "Chinese", "Modem",
			"Online", "Bellflower", "Wooper", "Passionflower", "Swalot", "Wailord", "Mawile", "Hitmonlee", "Litleo",
			"King", "Slakoth", "Spanish", "Goldfish", "Client", "Prince2", "Buzzwole", "Cornflakes", "Noble",
			"Amaryllis", "Kingambit", "Eel", "Natu", "Professional", "RoaringMoon", "Colombian", "Gooseberry",
			"WoChien", "Chespin", "Girafarig2", "Config", "Groudon", "Mango", "Aurorus", "Source", "Magnezone",
			"MindFlayer", "Basil", "Zoom", "Grapefruit", "Anaconda2", "Krookodile", "Meowscarada", "Tinkatink",
			"FarfetchD", "Poliwrath2", "Bellibolt", "Hippopotas", "Lampent", "Pastry", "Kartana", "HongKong",
			"Oricorio", "Lapras", "Version2", "Stunky", "Desktop", "Simisear", "Larvitar", "Gnome", "Sweets",
			"Exploud");

	public static final List<String> THOUSAND_NAMES_WORDS_EXPECTED = Arrays.asList("Combusken", "Virizion", "Memory",
			"ArticunoZeraora", "Falcon", "Sofa", "Iris", "Petunia", "IronJugulis", "Highchair", "Zygarde", "Violet",
			"Lisbon", "Copperajah", "Dragalge", "Tsareena", "Grubbin", "Azalea", "Analog", "Pawmi", "TigerLily",
			"Linoone", "Dragonite", "GougingFire", "Ranunculus", "Basculin", "Beef", "Necromancer", "Luge", "Platypus",
			"Gardevoir", "TingLu", "Finizen", "Decidueye", "Omastar", "Registeel", "Dondozo", "Competitive", "Dresser",
			"Suse", "HardwareSloth", "Artichoke", "Parameter", "Farigiraf", "Sandygast", "Interface", "Escavalier",
			"Weezing", "Pilchard", "Tranquill", "Salazzle", "Recliner", "Liver", "Swadloon", "Arcanine", "Global",
			"Pangoro", "Floragato", "Frogadier", "Tiefling", "Cosmog", "TurkeyShelgon", "Swimming", "Bombirdier",
			"Ekans", "Protected", "Boxing", "Trubbish", "Zigzagoon", "Houndoom", "Barcelona", "ValueFlareon", "Sentret",
			"Market", "Algorithm", "Drapion", "Azumarill", "Nasturtium", "Unique", "Orangutan", "NewDelhiTogekiss",
			"Zamazenta", "Scanner", "Seaking", "Ditto", "Thundurus", "Lobelia", "Cheese", "Cascoon", "Rocket", "Sole",
			"Vikavolt", "Sealeo", "Cloyster", "Hardware", "Klefki", "Chimecho", "Nidorino", "Spearow", "Charizard",
			"TapuKoko", "Hibiscus", "Chansey", "Jellyfish", "Apple", "Kiwi", "Mouse", "CarracostaOrange", "Wishiwashi",
			"Ninetales", "Spider", "Indian", "PolitoedBunnelby", "Mustard", "Handball", "OrthwormGrookey", "Nickit",
			"Dingo", "Enum", "SwedeComfey", "Dolphin", "Honeysuckle", "Rogue", "Forum", "Celery", "Primeape",
			"Salamander", "Radish", "VenomothPansear", "Mareep", "MarshtompKricketot", "Zinnia", "Bounsweet", "Tank",
			"Whiscash", "Herring", "KenyanArtificial", "Staryu", "Toronto", "Redcurrant", "Meeting", "Helianthus",
			"Supply", "Moscow", "GastlyWarrior", "Qwilfish", "Cleffa", "Simisage", "Castform", "Cod", "Marill",
			"Property", "Notepad", "Cabinet", "GimmighoulPansear", "Bayleef", "Cot", "Pig", "Crisps", "Oddish",
			"Blissey", "Golisopod", "Vietnamese", "Zapdos", "Elgyem", "Luxray", "Indeedee", "Freesia", "Haunter",
			"Penguin", "Decompressed", "Tomato", "Perrserker", "FlutterMane", "BounsweetGrubbin", "Miltank", "Moose",
			"Gholdengo", "Dialga", "Venusaur", "Shinx", "Disk", "Pomegranate", "Obstagoon", "Salmon", "Pumpkaboo",
			"Dewgong", "Rowing", "Tauros", "Public", "Luvdisc", "Eelektrik", "Dedenne", "BunkBed", "DiggersbyMelon",
			"Mayonnaise", "Scatterbug", "MespritBraviary", "Bench", "Delhi", "Frankfurt", "Zacian", "Dialer",
			"Butterfly", "Chandelure", "Calyrex", "Fletchling", "NorwegianRegex", "Beedrill", "Monitor", "Format",
			"Ivysaur", "Phone", "Spewpa", "Sugar", "Tennis", "Reshiram", "Hoppip", "Intern", "Biscuits", "Oranguru",
			"Camerupt", "Whale", "Voltorb", "Charcadet", "Jumpluff", "Houston", "Marmalade", "Simipour", "Cyclamen",
			"Glastrier", "Kenyan", "Honedge", "Stunfisk", "Document", "Regigigas", "Abomasnow", "Sawsbuck", "Glaceon",
			"Venomoth", "Phantump", "Migrator", "Malaysian", "Herbs", "SwedeFloatzel", "Shellos", "Amoonguss", "Two",
			"Clamperl", "Milan", "Lokix", "Duraludon", "Granbull", "Frigibax", "Chicken", "Comfey", "Sprigatito",
			"Coyote", "Shuckle", "Stock", "TwoMedicham", "Carrot", "Mabosstiff", "Megabyte", "Marshadow", "Politoed",
			"Open", "Cresselia", "Cauliflower", "Fish", "Chilean", "Helsinki", "Noivern", "Polteageist", "Throh",
			"Rapidash", "Chocolate", "Rampardos", "Swede", "Barboach", "Absol", "Glimmet", "Munchlax", "IronTreads",
			"RockingChair", "Passimian", "Azurill", "Feraligatr", "Arboliva", "Toucannon", "Scorpion", "Poliwhirl",
			"Pumpkin", "BaseballManaphy", "Ferroseed", "Stantler", "Brionne", "GrizzlyBear", "Beldum", "Grapploct",
			"MiraidonBarbaracle", "Desk", "Crobat", "Miraidon", "Necrozma", "Wartortle", "EelSalt", "Manectric",
			"Kirlia", "Dahlia", "Entei", "Kubfu", "Lilac", "Hind", "Drampa", "Amaura", "Class", "Cofagrigus", "Seel",
			"Italian", "Bangladeshi", "Shelf", "Review", "Gastrodon", "Garganacl", "System", "Excadrill", "Flygon",
			"Wobbuffet", "Sloth", "Roggenrola", "Patrat", "Toast", "Sizzlipede", "SaoPaulo", "PolarBear", "Cetitan",
			"Beheeyem", "Minccino", "Zarude", "Umbreon", "Five", "RaichuGothitelle", "Samurott", "Larvesta", "Ankara",
			"Bobsleigh", "Gimmighoul", "Croconaw", "Leafeon", "Leadership", "DuckBibarel", "Skiploom", "Shark",
			"CryogonalEspathra", "Ceruledge", "Noibat", "Wugtrio", "CornFlour", "Shared", "Whimsicott", "Marowak",
			"Training", "DocumentMabosstiff", "Dracovish", "Computer", "Database", "Pawniard", "Magikarp", "Metagross",
			"Verbena", "Trout", "Offline", "Venipede", "Seven", "Lurantis", "Rillaboom", "CheetahVanity", "Helioptile",
			"Uxie", "Rosemary", "Object", "WashingtonDc", "Sylveon", "Hamster", "BenchCoyote", "TapuBulu", "Frillish",
			"Onix", "Sectional", "Spam", "VegetablesHamster", "Victreebel", "Meditite", "Primrose", "Yveltal", "Seoul",
			"Sell", "Seedot", "Eternatus", "Treecko", "Spinach", "Poppy", "Xatu", "Mantelpiece", "Houndour",
			"GrapefruitRogue", "Psyduck", "SuicuneSnom", "Porridge", "Gumshoos", "Fraxure", "Ludicolo", "Type",
			"Vileplume", "Lotad", "LileepNidorina", "Heracross", "Serperior", "Cosmoem", "Pineco", "Intelligence",
			"Cream", "Buttercup", "Wigglytuff", "Update", "Technology", "Pincurchin", "Armarouge", "SalmonSentret",
			"Articuno", "Spinda", "ToucannonAxew", "Parrot", "Media", "Probopass", "Stockholm", "Metang", "Rolycoly",
			"CalyrexBouffalant", "Daffodil", "Xurkitree", "Aromatisse", "Ledyba", "Blackberry", "Exeggcute",
			"ArcanineKernel", "PropertyWitcher", "IronLeaves", "Landorus", "Lime", "Anorith", "SageChandelure",
			"Chingling", "Crocodile", "Chilli", "Leek", "Crabrawler", "Visual", "Scyther", "Togetic",
			"NidoranMaleDipplin", "Gladiolus", "Delphox", "Sage", "LileepSecretaire", "Dusclops", "Tandemaus",
			"Fennekin", "Commercial", "Larkspur", "Tinkatuff", "Khajit", "Motherboard", "Githyanki", "Wizard",
			"PumpkabooSlowking", "Seismitoad", "Arbok", "Pepper", "HakamoO", "Product", "Wrestling", "Begonia",
			"Suicune", "Gliscor", "National", "Lion", "Raikou", "CapeTown", "Minun", "Tirtouga", "Archeops", "Croagunk",
			"Goldeen", "Sharpedo", "Magnolia", "ScraftySerperior", "Shiftry", "Drifloon", "Link", "TrainingMexican",
			"Deino", "Kyurem", "Mumbai", "Tiger", "Goomy", "Krabby", "Lettuce", "NewYork", "Armchair", "Darmanitan",
			"Rhydon", "Rowlet", "Sardine", "Blipbug", "Toxapex", "Whirlipede", "Ursaring", "Yanmega", "Pidove", "Iraqi",
			"Pidgey", "Poliwrath", "Froslass", "MienshaoKeyword", "SpindaBunkBed", "Dhelmise", "MediaChansey",
			"Clefable", "Blaziken", "Utils", "Solgaleo", "Vulpix", "Jakarta", "PepperCustomer", "Fuecoco", "Baltoy",
			"ToxapexSpinarak", "Lacrosse", "Gulpin", "Montreal", "Hattrem", "Shiinotic", "Pelipper", "Johannesburg",
			"Tynamo", "Clobbopus", "RampardosBraviary", "Wailmer", "Scraggy", "Rome", "Version", "Vespiquen",
			"MasquerainQuilladin", "Clematis", "Cherrim", "List", "Geranium", "LombreSolosis", "Norwegian", "Reuniclus",
			"Golf", "Ketchup", "Arctibax", "Diggersby", "Syrian", "Espathra", "Lileep", "Scolipede", "KommoO", "Prague",
			"Raboot", "Sneasel", "CookieBaguette", "Hariyama", "Elephant", "Sinistcha", "Sunflower", "Explorer",
			"Camellia", "NewDelhi", "Vigoroth", "Taipei", "WooperKarrablast", "ArbolivaDelphinium", "Money", "Happiny",
			"Rice", "TapuFini", "CamelliaMigrator", "Mexican", "Shroodle", "Morgrem", "Fezandipiti", "ExplorerSilvally",
			"PsyduckIndeedee", "RegigigasRanger", "Lillipup", "BeanSprouts", "Bellsprout", "Duck", "Skateboarding",
			"Sparrow", "Cranidos", "Vegetables", "Kabuto", "Kangaskhan", "Noctowl", "Hash", "Eggs", "Copenhagen",
			"Vanilluxe", "Lugia", "LemonLugia", "Private", "Doe", "Gastly", "Poltchageist", "Forsythia", "Human",
			"Peas", "Sausage", "Armadillo", "Berserker", "Demon", "Coriander", "Live", "Biathlon", "Hard", "Smoochum",
			"Eevee", "Panda", "Beijing", "Luxio", "Santiago", "Magcargo", "Baseball", "Grape", "Madrid", "Monferno",
			"Pinsir", "Daisy", "Magearna", "Seahorse", "Persian", "Proprietary", "Terrakion", "Israeli", "Crawdaunt",
			"Dewpider", "Lombre", "Xerneas", "Inteleon", "Steenee", "Maschiff", "Witcher", "Horsea", "Frosmoth",
			"Mienfoo", "Snubbull", "Tinkaton", "Beartic", "Quilava", "Taekwondo", "ParameterEelektross", "Hawlucha",
			"Buneary", "Okidogi", "Dublin", "Dates", "Capsakid", "Grafaiai", "Sceptile", "Froakie", "Avalugg",
			"Strawberry", "Aggron", "Rellor", "Kernel", "Heather", "DatesSeismitoad", "Oinkologne", "Dragapult", "Bot",
			"Hydreigon", "ThrohTinkaton", "Pakistani", "BruteBonnet", "Enamorus", "Banana", "Wooloo", "Darumaka",
			"Wyrdeer", "TaipeiRosemary", "Value", "Volcarona", "Teddiursa", "Snom", "Dipplin", "Alakazam", "Ribombee",
			"Carbink", "Koala", "Coconut", "Mackerel", "Cradily", "PatratNoivern", "Nymble", "Hatenna", "Ninjask",
			"Ambipom", "ReuniclusGoldfish", "Tarountula", "Vienna", "Petilil", "Debug", "Cinderace", "Darkrai",
			"Polish", "MimeJr", "Cutiefly", "Hockey", "Sawk", "Mode", "Smeargle", "Emboar", "CradilyHind", "Lotus",
			"Mienshao", "Aron", "Honchkrow", "Pupitar", "Paris", "Scizor", "Archive", "Configuration", "Connected",
			"Araquanid", "Mankey", "SouthAfrican", "Vaporeon", "SmoochumAppletun", "Carracosta", "Print", "Salami",
			"Nacli", "Chewtle", "Kadabra", "Duskull", "Huntail", "Ducklett", "Plusle", "Cookie", "CodScreen",
			"Krokorok", "Naganadel", "Cryogonal", "Romanian", "Metapod", "Afghan", "Mantine", "IronValiant", "Virus",
			"Pheromosa", "Machoke", "IndianGastly", "Swellow", "Binacle", "Nihilego", "Nincada", "Futsal", "Warden",
			"Cake", "Druddigon", "Hamburg", "Vivillon", "Gothita", "Innovation", "Clam", "Cupboard", "Synergy",
			"Tablet", "Gabite", "Call", "BotKoala", "Palkia", "Scrafty", "Shanghai", "Headboard", "Marshtomp", "Azelf",
			"Varoom", "Exeggutor", "BegoniaMewtwo", "RedcurrantPlan", "Captcha", "Slowpoke", "KualaLumpur",
			"RioDeJaneiro", "Vanity", "Masquerain", "Relicanth", "Kyoto", "TinkatinkGrapefruit", "Zangoose",
			"SizzlipedeSwalot", "Page", "Hummingbird", "Prinplup", "Zurich", "Lemon", "Potato", "Smoliv", "Mosquito",
			"Servine", "Klink", "Urshifu", "Saffron", "Tangela", "Aegislash", "Mole", "Program", "Phlox", "Primarina",
			"DresserCow", "Leavanny", "Heatran", "Dewott", "Hedgehog", "Broccoli", "Alligator", "Koffing", "Appletun",
			"Flaaffy", "Nidoqueen", "LosAngeles", "Basculegion", "Torracat", "Rattata", "BarStool", "ScraggyUmbreon",
			"Wynaut", "Peach", "Risk", "Durant", "Mesprit", "Nightstand", "Audino", "Karate", "Glameow", "Jasmine",
			"Tyranitar", "Iranian", "Fletchinder", "Monk", "Wardrobe", "Pawmot", "CloysterDesk", "British", "Tornadus",
			"Bookcase", "Grookey", "Skiddo", "Carnivine", "Mothim", "Cheetah", "Silcoon", "Nosepass", "Piloswine",
			"Impidimp", "Pancham", "Vampire", "Mandibuzz", "Pixel", "Archen", "Wingull", "Raichu", "Guzzlord", "Ginger",
			"Tropius", "NidoranMale", "Security", "Boot", "Corsola", "Crustle", "Item", "Celebi", "Judo", "Toedscool",
			"Raticate", "Misdreavus", "ToucannonCramorant", "Istanbul", "Wisteria", "Donphan", "Gligar", "Regidrago",
			"Gigalith", "Ressource", "Surfing", "Scorbunny", "Wattrel", "Turkey", "Baxcalibur", "SweetPea",
			"WisteriaItem", "Gorebyss", "Gossifleur", "Latias", "Gengar", "Camel", "Togekiss", "Starly", "Astilbe",
			"Typhlosion", "Spreadsheet", "ChienPao", "Chat", "Spinarak", "Jynx", "Gourgeist", "Shelmet", "Keyword",
			"Phanpy", "Owl", "Cumin", "Hummus", "Poochyena", "Pichu", "Thread", "BeedrillWartortle", "Washstand",
			"ClobbopusQuiche", "Tangrowth", "Chinese", "LurantisPalafin", "Surskit", "Anemone", "Swirlix", "Dolliv",
			"Company", "Wooper", "Turtonator", "Mawile", "Hitmonlee", "AzumarillBayleef", "AronVictini", "Horse",
			"Slakoth", "Goldfish", "ZarudeMantelpiece", "Muk", "Brussels", "HatennaProgram", "Magmar", "Orthworm",
			"Bouffalant", "KyuremGrowlithe", "Eel", "Octopus", "RoaringMoon", "Colombian", "Loudred", "WoChien",
			"Whismur", "Baguette", "Cable", "Config", "Screen", "Mango", "Aurorus", "CrabrawlerWarrior", "Emolga",
			"Source", "Spaghetti", "Heliolisk", "Basil", "Zoom", "Grapefruit", "Krookodile", "Tinkatink", "FarfetchD",
			"Fruit", "Chicago", "Ledian", "Bellibolt", "Herdier", "BaseballSinistea", "Pastry", "Celesteela",
			"Corvisquire", "HongKong", "Oricorio", "PidgeySewaddle", "Stunky", "Raspberry", "Simisear", "Gnome",
			"Barraskewda");
}
